# Generated by Django 4.0.6 on 2022-08-01 20:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
