# Generated by Django 4.0.6 on 2022-08-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0009_remove_experience_description_remove_experience_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
