# Generated by Django 3.2 on 2022-08-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0012_experience_company_alter_experience_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
