# Generated by Django 3.2 on 2022-08-07 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0015_alter_post_user'),
        ('second_app', '0016_alter_userprofile_address'),
    ]

    operations = [
    ]
