# Generated by Django 3.2 on 2022-08-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0019_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='Dimension 600px X 671px', null=True, upload_to=''),
        ),
    ]
