# Generated by Django 3.2 on 2022-08-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0020_auto_20220808_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
