# Generated by Django 4.0.6 on 2022-08-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0017_comment'),
        ('second_app', '0021_alter_userprofile_address'),
    ]

    operations = [
    ]
