# Generated by Django 4.0.6 on 2022-08-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0022_merge_0017_comment_0021_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
