# Generated by Django 4.0.6 on 2022-08-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0023_alter_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
