# Generated by Django 4.0.6 on 2022-08-16 14:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0028_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('percentage', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
