# Generated by Django 4.0.6 on 2022-08-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0029_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.AddField(
            model_name='skill',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
