# Generated by Django 4.0.6 on 2022-08-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0031_rename_number_skill_pecentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='pecentage',
            new_name='percentage',
        ),
    ]
