# Generated by Django 4.0.6 on 2022-08-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0032_rename_pecentage_skill_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='color',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='text',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Skill Name'),
        ),
    ]
