# Generated by Django 4.0.6 on 2022-08-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0033_remove_skill_color_remove_skill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_color',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
