# Generated by Django 4.0.6 on 2022-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0036_about_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
